## Exceptions in IPython


In [3]:
import numpy as np

In [3]:
%run examples/ipython_bug.py

Exception: File `'examples/ipython_bug.py'` not found.

## 3.3 Files and the Operating System

In [16]:
path = 'a.txt'

In [17]:
f = open(path)

In [18]:
for line in f:
    pass

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 480: character maps to <undefined>

In [19]:
lines = [x.rstrip() for x in open(path)]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 480: character maps to <undefined>

In [20]:
f

<_io.TextIOWrapper name='a.txt' mode='r' encoding='cp1254'>

## Bytes and Unicode with Files

In [21]:
with open(path) as f:
     chars = f.read(10)

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 480: character maps to <undefined>

## 3.4 Conclusion

## CHAPTER 4
## NumPy Basics: Arrays and
## Vectorized Computation


In [22]:
 import numpy as np

In [23]:
my_arr = np.arange(100000)

In [24]:
my_list = list(range(100000))

In [26]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 997 µs


In [27]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 99.8 ms


* Numpy tabanlı algoritmalar daha az bellek kullanır.

## 4.1 The NumPy ndarray: A Multidimensional Array Object

In [28]:
data = np.random.rand(2, 3)

In [29]:
data

array([[0.96521453, 0.74474838, 0.33653715],
       [0.15199008, 0.91685404, 0.31695916]])

In [31]:
data * 10

array([[9.65214527, 7.44748376, 3.36537154],
       [1.51990084, 9.16854039, 3.16959158]])

In [32]:
data + data 

array([[1.93042905, 1.48949675, 0.67307431],
       [0.30398017, 1.83370808, 0.63391832]])

In [33]:
data.shape

(2, 3)

In [35]:
data.dtype

dtype('float64')

## Creating ndarrays

In [36]:
data1 = [6,7,8,0,1]

In [37]:
arr1 = np.array(data1)

In [38]:
arr1

array([6, 7, 8, 0, 1])

In [39]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [40]:
arr2 = np.array(data2)

In [41]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
arr2.ndim

2

In [43]:
arr2.shape

(2, 4)

In [44]:
arr2.dtype

dtype('int32')

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [53]:
np.empty((2, 3, 2)) #3 satır 2 sutundan olusan 2 tane matris

array([[[1.44014049e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 5.74084271e+169]],

       [[6.51172589e-091, 2.57111343e+184],
        [2.36715647e+179, 6.95350789e-042],
        [3.99910963e+252, 1.58692627e-047]]])

In [54]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data Types for ndarrays

In [55]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [57]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [58]:
arr1.dtype

dtype('float64')

In [59]:
arr2.dtype

dtype('int32')

In [60]:
arr = np.array([1, 2, 3, 4, 5])

In [61]:
arr.dtype

dtype('int32')

In [62]:
float_arr = arr.astype(np.float64)

In [63]:
float_arr.dtype

dtype('float64')

In [64]:
 arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [65]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [66]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [67]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [68]:
numeric_strings.astype(float)


array([ 1.25, -9.6 , 42.  ])

In [69]:
int_array = np.arange(10)

In [70]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [71]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [72]:
empty_uint32 = np.empty(8, dtype='u4')

In [73]:
empty_uint32

array([5046364, 6488169, 7274610, 7274611, 7602278, 5439520, 4980817,
       5439520], dtype=uint32)

## Arithmetic with NumPy Arrays

In [74]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [75]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [76]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [77]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
1 / arr 

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [79]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [80]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [81]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [82]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [83]:
arr = np.arange(10)

In [84]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr[5]

5

In [86]:
arr[5:8]

array([5, 6, 7])

In [87]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr_slice = arr[5:8]

In [89]:
arr_slice

array([5, 6, 7])

In [90]:
arr_slice[1] = 12345

In [91]:
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [92]:
arr_slice[:] = 64 #dizideki tüm değerlere atadı 

In [93]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [94]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [95]:
arr2d[2]

array([7, 8, 9])

In [96]:
arr2d[0][2]

3

In [97]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [99]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [100]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
old_values = arr3d[0].copy()

In [102]:
arr3d[0] = 42

In [103]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [104]:
arr3d[0] = old_values #eski degerine geri ceviriyoruz

In [105]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [106]:
arr3d[1, 0]

array([7, 8, 9])

In [107]:
x = arr3d[1]

In [108]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [109]:
x[0]

array([7, 8, 9])

## Indexing with slices

In [110]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [111]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [112]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [115]:
arr2d[1, :2]

array([4, 5])

In [117]:
arr2d[:2, 2]

array([3, 6])

In [118]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [119]:
arr2d[:2, 1:] = 0

In [120]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [5]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [6]:
data = np.random.randn(7, 4)

In [7]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [8]:
data

array([[-1.19532068, -0.65394391,  1.18341163, -1.18325013],
       [ 0.24028269,  0.5365607 ,  0.13080987, -0.33268673],
       [-0.86069667,  0.85511919,  1.31812086,  0.5968625 ],
       [ 1.28906442, -0.86051749,  0.00466062,  0.77864673],
       [-0.22704705,  0.48586865,  0.59986074,  1.21317674],
       [-1.15377797,  1.20300773,  0.34161944, -0.59695552],
       [ 0.66492098,  0.04776623,  0.15972772, -0.11827614]])

In [9]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [10]:
data[names == 'Bob']

array([[-1.19532068, -0.65394391,  1.18341163, -1.18325013],
       [ 1.28906442, -0.86051749,  0.00466062,  0.77864673]])

In [11]:
data[names == 'Bob', 2:]

array([[ 1.18341163, -1.18325013],
       [ 0.00466062,  0.77864673]])

In [12]:
data[names == 'Bob', 3]

array([-1.18325013,  0.77864673])

In [13]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [14]:
data[~(names == 'Bob')] # != in aynısı

array([[ 0.24028269,  0.5365607 ,  0.13080987, -0.33268673],
       [-0.86069667,  0.85511919,  1.31812086,  0.5968625 ],
       [-0.22704705,  0.48586865,  0.59986074,  1.21317674],
       [-1.15377797,  1.20300773,  0.34161944, -0.59695552],
       [ 0.66492098,  0.04776623,  0.15972772, -0.11827614]])

In [15]:
cond = names == 'Bob'

In [16]:
data[~cond]

array([[ 0.24028269,  0.5365607 ,  0.13080987, -0.33268673],
       [-0.86069667,  0.85511919,  1.31812086,  0.5968625 ],
       [-0.22704705,  0.48586865,  0.59986074,  1.21317674],
       [-1.15377797,  1.20300773,  0.34161944, -0.59695552],
       [ 0.66492098,  0.04776623,  0.15972772, -0.11827614]])

In [17]:
mask = (names == 'Bob') | (names == 'Will')

In [18]:
mask

array([ True, False,  True,  True,  True, False, False])

In [19]:
data[mask]

array([[-1.19532068, -0.65394391,  1.18341163, -1.18325013],
       [-0.86069667,  0.85511919,  1.31812086,  0.5968625 ],
       [ 1.28906442, -0.86051749,  0.00466062,  0.77864673],
       [-0.22704705,  0.48586865,  0.59986074,  1.21317674]])

In [20]:
data[data < 0] = 0 #0 dan küçük negatif degerleri sıfıra eşitledik.

In [21]:
data

array([[0.        , 0.        , 1.18341163, 0.        ],
       [0.24028269, 0.5365607 , 0.13080987, 0.        ],
       [0.        , 0.85511919, 1.31812086, 0.5968625 ],
       [1.28906442, 0.        , 0.00466062, 0.77864673],
       [0.        , 0.48586865, 0.59986074, 1.21317674],
       [0.        , 1.20300773, 0.34161944, 0.        ],
       [0.66492098, 0.04776623, 0.15972772, 0.        ]])

In [22]:
data[names != 'Joe'] = 7

In [23]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.24028269, 0.5365607 , 0.13080987, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.20300773, 0.34161944, 0.        ],
       [0.66492098, 0.04776623, 0.15972772, 0.        ]])

## Fancy Indexing

* İnteger diziler kullanarak indekslemeyi tanımlamak.

In [11]:
arr = np.empty((8, 4))

In [12]:
for i in range(8):
    arr[i] = i

In [13]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [14]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [15]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [16]:
arr = np.arange(32).reshape((8, 4))

In [17]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [18]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] #1.satır 0.sutun veya 5.satır 3.sutun gibi.

array([ 4, 23, 29, 10])

In [19]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [20]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays and Swapping Axes

In [21]:
arr = np.arange(15).reshape((3, 5))

In [22]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [24]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [25]:
arr = np.arange(16).reshape((2, 2, 4))

In [26]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [27]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [28]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [32]:
arr.swapaxes(1, 2)


array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 4.2 Universal Functions: Fast Element-Wise Array
## Functions

In [33]:
arr = np.arange(10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.sqrt(arr) #karekökünü alır.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
np.exp(arr) #tüm öğelerin üstelini hesaplaması

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [38]:
x = np.random.randn(8)

In [39]:
y = np.random.randn(8)

In [40]:
x

array([ 0.61994099,  0.09279098, -0.48053172,  0.43441583, -1.58739969,
        0.46311007, -0.56358336, -0.25294086])

In [41]:
y

array([ 1.36685015, -0.75970534,  0.2974134 ,  0.45574567,  0.15575212,
       -0.89344801, -0.82530104, -2.06755738])

In [42]:
np.maximum(x, y)

array([ 1.36685015,  0.09279098,  0.2974134 ,  0.45574567,  0.15575212,
        0.46311007, -0.56358336, -0.25294086])

In [43]:
arr = np.random.randn(7) * 5

In [44]:
arr

array([2.4134403 , 3.36470419, 7.2823886 , 5.55922702, 2.31816842,
       0.88864181, 7.11584572])

In [45]:
remainder, whole_part = np.modf(arr)

In [46]:
remainder

array([0.4134403 , 0.36470419, 0.2823886 , 0.55922702, 0.31816842,
       0.88864181, 0.11584572])

In [47]:
whole_part

array([2., 3., 7., 5., 2., 0., 7.])

In [48]:
arr

array([2.4134403 , 3.36470419, 7.2823886 , 5.55922702, 2.31816842,
       0.88864181, 7.11584572])

In [49]:
np.sqrt(arr)

array([1.55352512, 1.834313  , 2.69859011, 2.35780131, 1.52255326,
       0.942678  , 2.66755426])

In [50]:
np.sqrt(arr, arr)

array([1.55352512, 1.834313  , 2.69859011, 2.35780131, 1.52255326,
       0.942678  , 2.66755426])

In [51]:
arr

array([1.55352512, 1.834313  , 2.69859011, 2.35780131, 1.52255326,
       0.942678  , 2.66755426])

## 4.3 Array-Oriented Programming with Arrays

In [52]:
points = np.arange(-5, 5, 0.01)

In [53]:
xs, ys = np.meshgrid(points, points)

In [54]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [55]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [56]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [57]:
import matplotlib.pyplot as plt

In [58]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [59]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [60]:
cond = np.array([True, False, True, True, False])

In [61]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]

In [62]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [63]:
result = np.where(cond, xarr, yarr)

In [64]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])